### ISSUE TITLE
prepflog tarball is rather bizarre

### ISSUE THREAD

**Issue by quanah** [johnfawcett/prepflog#1]
A number of issues:

1) Filename is 0.4.1.tgz instead of prepflog-0.4.1.tgz

2) after extracting, the layout is:
quanah@zre-ldap001:~/p4/zimbra/main/ThirdParty/prepflog/src/prepflog-0.4.1$ ls -l
total 8
drwxrwxr-x 2 quanah quanah 4096 Aug 16 15:16 release
drwxrwxr-x 3 quanah quanah 4096 Aug 16 15:16 source
quanah@zre-ldap001:~/p4/zimbra/main/ThirdParty/prepflog/src/prepflog-0.4.1$ ls source/
prepflog-0.4.1
quanah@zre-ldap001:~/p4/zimbra/main/ThirdParty/prepflog/src/prepflog-0.4.1$ ls release/
prepflog-0.4.1.tgz  prepflog-0.4.1.tgz.sig

I.e., the release contains itself (yuck!), and the actual package is down further in a source/prepflog-<version> directory.

**Comment by johnfawcett** [comment]
The tar you downloaded contained a separate source and release directory. This is a left over from the previous hosting of the project. The tar file in the release directory is the one you needed. However to avoid confusion I have simplified the directory structure removing the distinction between release and source and let github do the release packaging.

**Comment by quanah** [comment]
I understand what it contained. ;)  Thanks for the new release!
